	CREATE DATABASE inlock_games_tarde
	GO
	
	USE inlock_games_tarde
	GO

	CREATE TABLE ESTUDIO(
	idEstudio SMALLINT PRIMARY KEY IDENTITY (1,1),
	nomeEstudio VARCHAR (300) NOT NULL
 	);
	GO

	CREATE TABLE JOGOS(
	idJogo SMALLINT PRIMARY KEY IDENTITY (1,1),
	idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio),
	nomeJogo VARCHAR(500) NOT NULL,
	valor MONEY NOT NULL,
	dataLancamento DATE NOT NULL,
	descricao VARCHAR(500)
	);
	GO

	CREATE TABLE TIPOUSUARIO(
	idTipoU TINYINT PRIMARY KEY IDENTITY (1,1),
	titulo VARCHAR (100) NOT NULL
	);
	GO

	CREATE TABLE USUARIO(
	idUsurio INT PRIMARY KEY IDENTITY (1,1),
	idTipoU TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoU),
	email VARCHAR (256) UNIQUE NOT NULL,
	senha VARCHAR (256) NOT NULL,
	);
	GO